### ISSUE TITLE
CI Coverage Test

### ISSUE THREAD

**Issue by AntoniosBarotsis** [AntoniosBarotsis/MLFS_Java#1]
Automatically generate coverage reports through Travis CI and check whether the % of line coverage is bigger than a specific threshold before pushing to master/merging PRs

**Comment by sudiptog81** [comment]
See [CodeCov](https://codecov.io/), the [GitHub App integration](https://github.com/apps/codecov) that can be run as a check on PRs and some way to generate code coverage reports using jUnit, like JaCoCo.
